route:
 group_by: [cluster]
 # If an alert isn't caught by a route, send it slack.
 receiver: slack
 routes:
  # Send severity=slack alerts to slack.
  - match:
      severity: slack
    receiver: slack

receivers:
- name: slack
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: '#alertmanager'
