route:
  receiver: slack

receivers:
  - name: slack
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alertmanager'
