---
  - hosts: all
    gather_facts: no

    tasks:
      - name: Wait for SSH
        local_action: wait_for port=22 host={% if ansible_ssh_host is defined %}{{ ansible_ssh_host }}{% else %}{{ inventory_hostname }}{% endif %}
      - name: Install the package apache2
        apt:
          name: apache2
          update_cache: yes
          state: present
